minimum_pre_commit_version: 2.15.0
exclude: (html|csv|svg)$
default_stages: [
    commit,
    merge-commit,
    push,
    prepare-commit-msg,
    commit-msg,
    post-checkout,
    post-commit,
    post-merge,
    post-rewrite
]
ci:
    autofix_prs: false
repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        require_serial: true
        types_or: [python, pyi]