version: '3.8'

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - DATABASE_TYPE=postgresql
      - DATABASE_DRIVER=psycopg2
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres
    volumes:
      - ./app:/root/src/app
      - ./scripts:/root/src/scripts
      - ./alembic:/root/src/alembic
    command: ["/bin/bash", "-c", "source ~/.bashrc && scripts/docker_run_dev.sh"]

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
