# Multi-Stage build with build and deploy jobs to deploy on Azure VM

name: Build and deploy FastApi Python app to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  APP_NAME: 'fastapi'
  WORKING_DIRECTORY: '.'
  STARTUP_COMMAND: 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub 
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: pip install -r requirements.txt

      - name: Display structure of current files
        run: ls -R
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}
          path: |
            ${{ env.WORKING_DIRECTORY }}
            !venv/
            !.git/
            !.github/


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.APP_NAME }}
          path: ${{ env.WORKING_DIRECTORY }}

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ env.WORKING_DIRECTORY }}
      
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client
            
      - name: Copy artifact to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VM_IP_ADDRESS }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: ${{ env.WORKING_DIRECTORY }}
          target: '/home/${{ vars.VM_USERNAME }}'

      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VM_IP_ADDRESS }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip install -r requirements.txt
    
      - name: Start App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VM_IP_ADDRESS }}
          username: ${{ vars.VM_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            ${{ env.STARTUP_COMMAND }}

      - name: Logout of Azure VM
        run: |
          ssh-agent -k
          