# Workflow for Unit Testing and Code Coverage

name: Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  testing:
    runs-on: ubuntu-latest

    environment: 
      name: 'Testing'
      
    env:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_HOSTNAME: ${{ vars.DATABASE_HOSTNAME }}
      DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      DATABASE_PORT: ${{ vars.DATABASE_PORT }}
      DATABASE_TYPE: ${{ vars.DATABASE_TYPE }}
      DATABASE_DRIVER: ${{ vars.DATABASE_DRIVER }}
      ALGORITHM: ${{ vars.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: ${{ vars.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ vars.DATABASE_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
          
      - name: Install project dependencies
        run: pip install -r requirements-test.txt

      - name: Run tests and generate code coverage report
        run: |
            cd $GITHUB_WORKSPACE
            pytest --cov-report=xml --cov=app

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage.xml
