# Workflow for Unit Testing and Code Coverage

name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:

    name: Linting and Formatting
    runs-on: ubuntu-latest

    environment:
      name: 'Testing'

    env:
      GITHUB_PAGES_BRANCH: gh-pages

    permissions:
      contents: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: psf/black@stable
        with:
          jupyter: true

      # - name: Run Snyk to check for vulnerabilities
      #   uses: snyk/actions/python@master
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --sarif-file-output=snyk.sarif

      # - name: Upload result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: snyk.sarif

      # - name: Run Super-Linter
      #   uses: github/super-linter@v5
      #   env:
      #     DEFAULT_BRANCH: main
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DISABLE_ERRORS: true
      #     VALIDATE_ALL_CODEBASE: true
      #     OUTPUT_DETAILS: detailed


  test:
    name: Testing
    runs-on: ubuntu-latest
    needs: lint

    environment:
      name: 'Testing'

    env:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_HOSTNAME: ${{ vars.DATABASE_HOSTNAME }}
      DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      DATABASE_PORT: ${{ vars.DATABASE_PORT }}
      DATABASE_TYPE: ${{ vars.DATABASE_TYPE }}
      DATABASE_DRIVER: ${{ vars.DATABASE_DRIVER }}
      ALGORITHM: ${{ vars.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ vars.ACCESS_TOKEN_EXPIRE_MINUTES }}

    # services:
    #   postgres:
    #     image: postgres:13.3
    #     env:
    #       POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    #       POSTGRES_DB: ${{ vars.DATABASE_NAME }}_test # SQLAlchemy configured the same way
    #     ports:
    #       - 5432:5432
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    # strategy:
    #   matrix:
    #     python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}

      # - name: Upgrade pip
      #   run: python -m pip install --upgrade pip

      # - name: Install project dependencies
      #   run: pip install -r requirements-test.txt

      # - name: Run tests and generate code coverage report
      #   run: |
      #       cd $GITHUB_WORKSPACE
      #       pytest --cov-report=xml --cov=app

      # - name: Upload coverage report to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Upload code coverage report as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: code-coverage-report
      #     path: ./coverage.xml


  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   needs: test

  #   environment:
  #     name: 'Testing'

  #   env:
  #     APP_NAME: fastapi-docker
  #     APP_VERSION: ${{ github.sha }}

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup docker buildx
  #       id: buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to docker
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

  #     - name: Build and push docker image
  #       id: docker_build
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.APP_VERSION }}
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max

  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}


  multi-platform-build:
    name: Multi-platform Build
    runs-on: ubuntu-latest
    needs: test

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    environment:
      name: 'Testing'

    env:
      APP_NAME: fastapi-docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.docker_build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1


  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: multi-platform-build

    environment:
      name: 'Testing'

    env:
      APP_NAME: fastapi-docker
      APP_VERSION: ${{ github.sha }}

    steps:
      -
        name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}@sha256:%s ' *)
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ steps.meta.outputs.version }}
